site_name: TableGPT Agent

theme:
  name: "material"
  features:
    - navigation.footer
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
  icon:
    edit: material/pencil 
    view: material/eye
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - mkdocs-jupyter
  - mkdocstrings
  - search

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"

nav:
  - Home: index.md
  - Tutorials:
    - 'Quick Start': tutorials/quick-start.ipynb
    - 'Chat on tablular data': tutorials/chat-on-tabular-data.ipynb
    - 'Continue Analysis on Generated Charts': tutorials/continue-analysis-on-generated-charts.ipynb
  - 'How-To Guides':
    - 'Enhance TableGPT Agent with RAG': howto/retrieval.ipynb
    - 'Persist Messages': howto/persist-messages.ipynb
    - 'Incluster Code Execution': howto/incluster-code-execution.md
    - 'Normalize Datasets': howto/normalize-datasets.ipynb
    - 'Cleanup Error Trace': howto/cleanup-error-trace.md
    - 'Customize Table Info': howto/customize-table-info.md
  - Reference: reference.md
  - Explanation:
    - 'Agent Workflow': explanation/agent-workflow.md
    - 'File Reading': explanation/file-reading.ipynb
    - 'Code Sandbox': explanation/code-sandbox.md
    - 'IPython Startup Scripts': explanation/ipython-startup-scripts.md

repo_name: tablegpt/tablegpt-agent
repo_url: https://github.com/tablegpt/tablegpt-agent
edit_uri: edit/main/docs/
